config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  post '/product/:id/review/new', to: 'review#create'

  resources :products
  resources :users
  resources :reviews
  resources :products do
    resources :reviews
  end
  #resources :users, except: :index

  # static pages routes, not connected to models
  get '/help',    to: 'static_pages#help', as: 'helf'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # dynamic routes
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/review/new',  to: 'products#index'




  # login routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/views/partials/_footer.html.erb
<footer class="footer">
  <small>
    Redmart made by Tze Wei
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    
    </ul>
  </nav>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Redmart", root_path, class: 'navbar-brand' %>
      <!-- <a class="navbar-brand" href="#">Redmart</a> -->
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>

        <% if logged_in? %> <!-- Already logged in_-->
          <% if current_user.admin?%>
            <li><%= link_to "All Users", users_path %></li>
            <li><%= link_to "All Reviews", reviews_path %></li>
            <li><%= link_to "All Products", products_path %></li>
            <li><%= link_to "My Profile", current_user %></li>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "My Profiles", current_user %></li>
            <li><%= link_to "All Reviews", reviews_path %></li>
            <li><%= link_to "All Products", products_path %></li>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <% end %>

        <% else %>

          <li><%= link_to "Signup", signup_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>