config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  post '/product/:id/review/new', to: 'review#create'

  resources :products
  resources :users
  resources :reviews
  resources :products do
    resources :reviews
  end
  #resources :users, except: :index

  # static pages routes, not connected to models
  get '/help',    to: 'static_pages#help', as: 'helf'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # dynamic routes
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/review/new',  to: 'products#index'




  # login routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }


  # VALIDATION
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates(  :name,
              presence: true,
              length: { maximum: 50, message: 'Input name is too long!' }
  )

  validates(  :email,
              presence: true,
              length: { maximum: 75 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }
  )
  validates(  :password,
              presence: true,
              length: { minimum: 4 },
              allow_nil: true
  )

# FOR HASHING PASSWORD
  has_secure_password


# Relationship model
  has_many :reviews, dependent: :destroy
  has_many :products, through: :reviews


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # setting default user, based on the id
  before_action :set_user,       only:   [:edit, :update, :destroy]

  # check if already logged in
  before_action :require_login,  only:   [:show, :edit, :update, :destroy]

  # check if correct user
  before_action :correct_user,   only:   [:edit, :update]

  # check if needs log out again
  before_action :require_logout, only:   [:new]

  before_action :admin_user,     only: :destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in(@user)
        flash[:success] = 'User was successfully created.'
        format.html { redirect_to current_user }
        # format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = 'User was successfully updated.'
        format.html { redirect_to @user }
        # format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully deleted.' }
      # format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def permitted_user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :address, :password, :password_confirmation)
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])

      unless current_user?(@user)
        flash[:warning] = "Wrong person"
        redirect_to root_url
      end
    end

    def require_logout
      if logged_in?
        flash[:warning] = "You must logged out to create a new user"
        redirect_to(root_url)
      end
    end

    # Confirms an admin user.
     def admin_user
       redirect_to(root_url) unless current_user.admin?
     end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!-- <%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :password_digest %>
    <%= f.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->

app/views/users/_user.html.erb
<li>
  <%#= gravatar_for user, size: 50 %>
  <%#= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                                    data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        </div>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

<!-- <%= link_to 'Show', @user %> | -->
<%= link_to 'Cancel', @user %>

app/views/users/index.html.erb
<h1>Details of All Users</h1>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Address</th>

        <% if current_user.admin?%>
          <th>Password</th>
        <% end %>

      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.address %></td>
          <td><% if current_user.admin?%>
                <%= user.password_digest %>
              <% end %>
          </td>


          <td><%= link_to 'Show', user %></td>
          <td><% if current_user.admin?%>
                  <%= link_to 'Edit', edit_user_path(user) %>
                <% end %>
          </td>
          <td><% if current_user.admin? && !current_user?(user) %>
                | <%= link_to "delete", user, method: :delete,
                                              data: { confirm: "You sure?" } %>
              <% end %>
          </td>
          <!-- <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<%= link_to 'Back to Profile', current_user %>
<!-- <%= link_to 'New User', new_user_path %>


<% provide(:title, 'All users') %>
<h1>All users</h1>

<%#= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%#= will_paginate %> -->

app/views/users/new.html.erb
<h1>Sign up</h1>



<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        </div>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email%>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :address%>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'Back', root_path %>
  </div>
</div>

app/views/users/show.html.erb
<h1> Profile of <%= @user.name %> </h1>

<h3>Details: </h3>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Address</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @user.name %></td>
        <td><%= @user.email %></td>
        <td><%= @user.address %></td>
        <td><%= link_to 'Edit', edit_user_path(@user) %></td>
        <td>
          <% if current_user.admin?%>
            <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>


<% if @user.reviews.any? %>
  <!-- <h3><%= @user.name %> has a total of <%= @user.reviews.count %> reviews:</h3> -->
  <h3><%= @user.name %> has a total of <%= pluralize(@user.reviews.count, "review")%></h3>
<div class="table-responsive">
  <table class="table">
      <thead>
        <tr>
          <th>Product Name </th>
          <th>Reviews </th>
          <th>Created Date</th>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td><%= review.product.productname %> </td>
            <td><%= review.userreview %> </td>
            <td><%= review.created_at %></td>
            <td><%= link_to 'Details', review_path(review) %></td>
            <td><%= link_to 'Edit', edit_review_path(review) %></td>
            <td><%= link_to 'Delete', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>

<%else%>
  <h3>User has no review!</h3>
<% end %>

<%= link_to 'Back to main', root_path %>