config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  post '/product/:id/review/new', to: 'review#create'

  resources :products
  resources :users
  resources :reviews
  resources :products do
    resources :reviews
  end
  #resources :users, except: :index

  # static pages routes, not connected to models
  get '/help',    to: 'static_pages#help', as: 'helf'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # dynamic routes
  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/review/new',  to: 'products#index'




  # login routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  has_many :users, through: :review

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show,  :update]
  before_action :admin_user,  only: [:destroy, :edit]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @review = current_user.reviews.build

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:productname, :price)
    end

    # Confirms an admin user.
     def admin_user
       redirect_to(root_url) unless current_user.admin?
     end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :productname %>
    <%= f.text_field :productname %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Products</h1>

<div class="table-responsive">
  <table class="table">
  <thead>
    <tr>
      <th>Productname</th>
      <th>Price $</th>

    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.productname %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Add Review', product_path(product) %></td>
        <% if current_user.admin?%>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<% if current_user.admin?%>
<%= link_to 'New Product', new_product_path %>  |
<% end %>
<%= link_to 'Back to Profile', current_user %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Product page of <%=@product.productname%></h1>

<div class="table-responsive">
  <table class="table">
  <thead>
    <tr>
      <th>Review</th>
      <th>Price $</th>
      <th>Reviewed by</th>

    </tr>
  </thead>

  <tbody>
    <% @product.reviews.each do |review| %>
      <tr>
        <td><%= review.userreview %> </td>
        <td><%= review.product.price %></td>
        <td><%= review.user.name %> </td>
        <% if current_user.admin?%>
          <td><%= link_to 'Edit', edit_review_path(review) %></td>
          <td><%= link_to 'Delete', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
  </tbody>
</table>
</div>

<!-- <p>shared/user_info</p> -->
  <h1><%= current_user.name %></h1>
<span><%= current_user.name %> currently has total of </span>
<span><%= pluralize(current_user.reviews.count, "review")%>

<!-- shared/micropost form -->
<%= form_for([@product, @product.reviews.build]) do |f| %>
  <%#= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :userreview, placeholder: "Compose new review"%>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>